server:
  port: 8081

spring:
  application:
    name : Employee-Service
#  zipkin:
#    base-url: http://127.0.0.1:9411/

# Enable when no separate Config server
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost